version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: Meraviglia
      POSTGRES_PASSWORD: Meraviglia9
      POSTGRES_DB: Restaurant_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432